wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716864451
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
