wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716263822
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.17.0
      6: 4.41.0
      8:
      - 5
      13: linux-x86_64
